version: "3"
services:
  sonarqubev8:
    image: sonarqube:8.2-community
    hostname: sonarqubev8
    container_name: sonarqubev8
    depends_on:
      - dbv8
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://dbv8:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - v8sonarqube_data:/opt/sonarqube/data
      - v8sonarqube_extensions:/opt/sonarqube/extensions
      - v8sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  dbv8:
    image: postgres:13
    hostname: postgresql
    container_name: postgresqlv8
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - v8postgresql:/var/lib/postgresql
      - v8postgresql_data:/var/lib/postgresql/data

volumes:
  v8sonarqube_data:
  v8sonarqube_extensions:
  v8sonarqube_logs:
  v8postgresql:
  v8postgresql_data: